[package]
name = "clstr"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "clstr"
path = "src/main.rs"

[target.'cfg(not(test))'.dependencies]
clap = { version = "4.5.19", features = ["cargo"] }
bio = "2.0.3"
flate2 = "1.0.34"
